# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
java_version=25

# Mod Properties
mod_version=0.0.1
group=net.dimaskama.voicemessagestranscriber

# Dependencies
fabric_api_version=0.161.0+26.2
voicemessages_version=1.0.13-26.2
whisper_jni_version=1.7.1
modmenu_version=20.0.3
voicechat_version=fabric-2.6.24+26.2
